/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "clfgsfdnyvdjgcevafzw"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNsZmdzZmRueXZkamdjZXZhZnp3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzk3ODU5MjUsImV4cCI6MjA5NTM2MTkyNX0.nOZUSBb9X5ewSHjs7kqb-ZYbnnWPvHtUQNbd_Vr-LPM"